language: php

sudo: false

git:
    depth: 1

env:
    global:
        - TASK_TESTS=1
        - TASK_TESTS_COVERAGE=0
        - TASK_CS=1
        - TASK_SCA=0

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: DEPLOY=yes TASK_TESTS_COVERAGE=1
        - php: 7.1
          env: TASK_SCA=1
        - php: 5.3
          env: SKIP_LINT_TEST_CASES=1 COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.4
          env: SKIP_LINT_TEST_CASES=1
        - php: 5.5
          env: SKIP_LINT_TEST_CASES=1
        - php: 5.6
        - php: 7.1
          env: SYMFONY_VERSION="^2.8"
        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        - php: hhvm-3.9
          env: SKIP_LINT_TEST_CASES=1
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm
          env: SKIP_LINT_TEST_CASES=1
          sudo: required
          dist: trusty
          group: edge

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    # XDebug preparation:
    # - for tag building for release we don't need to collect code coverage, let us turn off xdebug completely
    # - for regular build we care about collecting code coverage, let us turn off xdebug only for installation part
    - if [ $TRAVIS_TAG ]; then phpenv config-rm xdebug.ini || return 0; fi
    - if [ -z $TRAVIS_TAG ]; then mv $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini $HOME/xdebug.ini || return 0; fi

    # for building a tag release we don't need to run SCA tools, collect code coverage or self-fix CS
    - if [ $TRAVIS_TAG ]; then export TASK_SCA=0; fi
    - if [ $TRAVIS_TAG ]; then export TASK_TESTS_COVERAGE=0; fi
    - if [ $TRAVIS_TAG ]; then export TASK_CS=0; fi

    # Composer: boost installation
    - travis_retry composer global require hirak/prestissimo

    # Composer: enforce given Symfony components version
    - 'if [ "$SYMFONY_VERSION" != "" ]; then sed -i "s/\"symfony\/\([^\"]*\)\": \"^2[^\"]*\"/\"symfony\/\1\": \"$SYMFONY_VERSION\"/g" composer.json; fi'

    # display tasks configuration for a job
    - set | grep ^TASK | sort

install:
    - travis_retry composer update $COMPOSER_FLAGS --no-interaction

script:
    - if [ $TASK_SCA == 1 ]; then php php-cs-fixer fix --rules declare_strict_types -q; fi

    - if [ $TASK_TESTS_COVERAGE == 1 ]; then phpenv config-add $HOME/xdebug.ini || return 0; fi
    - if [ $TASK_TESTS == 1 ]; then vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml; fi
    - if [ $TASK_TESTS_COVERAGE == 1 ]; then phpenv config-rm $HOME/xdebug.ini || return 0; fi

    - if [ $TASK_SCA == 1 ]; then git checkout . -q; fi

    - if [ $TASK_CS == 1 ]; then php php-cs-fixer --diff --dry-run -v fix; fi

after_success:
    - if [ $TASK_TESTS_COVERAGE == 1 ]; then php vendor/bin/coveralls -v; fi

before_deploy:
    # install box2
    - curl -LSs http://box-project.github.io/box2/installer.php | php
    - php box.phar --version

    # ensure that deps will work on lowest supported PHP version
    - |
      sed -i 's#"config":\s*{#"config": {\n        "platform": {"php": "5.3.6"},#' composer.json
    # update deps to highest possible for lowest supported PHP version
    - composer update --no-dev --no-interaction --optimize-autoloader --prefer-stable

    # build phar file
    - php -d phar.readonly=false box.phar build

deploy:
    provider: releases
    api_key:
        secure: K9NKi7X1OPz898fxtVc1RfWrSI+4hTFFYOik932wTz1jC4dQJ64Khh1LV9frA1+JiDS3+R6TvmQtpzbkX3y4L75UrSnP1ADH5wfMYIVmydG3ZjTMo8SWQWHmRMh3ORAKTMMpjl4Q7EkRkLp6RncKe+FAFPP5mgv55mtIMaE4qUk=
    file: php-cs-fixer.phar
    skip_cleanup: true
    on:
        repo: FriendsOfPHP/PHP-CS-Fixer
        tags: true
        condition: $DEPLOY = yes
