language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.3
          env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: SYMFONY_VERSION="~2.7"
        - php: 5.6
          env: SYMFONY_VERSION="~3.0@dev" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm
          sudo: required
          dist: trusty
          group: edge

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - mv $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini $HOME/xdebug.ini || return 0
    - 'if [ "$SYMFONY_VERSION" != "" ]; then sed -i "s/\"symfony\/\([^\"]*\)\": \"[^\"]*\"/\"symfony\/\1\": \"$SYMFONY_VERSION\"/g" composer.json; fi'

install:
    - travis_retry composer global require hirak/prestissimo
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - cp $HOME/xdebug.ini $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
    - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0
    - php php-cs-fixer --diff --dry-run -v fix

after_success:
    - php vendor/bin/coveralls -v
