language: php

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.3
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.4
        - php: 5.5
        - php: 5.6
          env: DEPLOY=yes
        - php: 7.0
          env: SYMFONY_VERSION="~2.8"
        - php: 7.0
          env: LINT_TEST_CASES=1
        - php: 7.1
          env: LINT_TEST_CASES=1
        # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm
          sudo: required
          dist: trusty
          group: edge

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - git config --global github.accesstoken 5e7538aa415005c606ea68de2bbbade0409b4b8c
    - mv $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini $HOME/xdebug.ini || return 0
    - travis_retry composer global require hirak/prestissimo
    - 'if [ "$SYMFONY_VERSION" != "" ]; then sed -i "s/\"symfony\/\([^\"]*\)\": \"[^\"]*\"/\"symfony\/\1\": \"$SYMFONY_VERSION\"/g" composer.json; fi'

install:
    - travis_retry composer update $COMPOSER_FLAGS --no-interaction

script:
    - cp $HOME/xdebug.ini $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
    - composer test-ci
    - phpenv config-rm xdebug.ini || return 0
    - php php-cs-fixer --diff --dry-run -v fix

after_success:
    - php vendor/bin/coveralls -v

before_deploy:
    # install box2
    - curl -LSs http://box-project.github.io/box2/installer.php | php
    - php box.phar --version
    # ensure that deps will work on lowest supported PHP version
    - |
      sed -i 's#"config":\s*{#"config": {\n        "platform": {"php": "5.3.6"},#' composer.json
    # update deps to highest possible for lowest supported PHP version
    - composer update --no-dev --no-interaction --optimize-autoloader --prefer-stable
    # build phar file
    - php -d phar.readonly=false box.phar build

deploy:
    provider: releases
    api_key:
        secure: K9NKi7X1OPz898fxtVc1RfWrSI+4hTFFYOik932wTz1jC4dQJ64Khh1LV9frA1+JiDS3+R6TvmQtpzbkX3y4L75UrSnP1ADH5wfMYIVmydG3ZjTMo8SWQWHmRMh3ORAKTMMpjl4Q7EkRkLp6RncKe+FAFPP5mgv55mtIMaE4qUk=
    file: php-cs-fixer.phar
    skip_cleanup: true
    on:
        repo: FriendsOfPHP/PHP-CS-Fixer
        tags: true
        condition: $DEPLOY = yes
