dist: xenial
os: linux

language: php

git:
    depth: 10

cache:
    directories:
        - $HOME/.composer
        - $HOME/bin

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--optimize-autoloader --no-interaction --no-progress"
        - COMPOSER_FLAGS=""

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

jobs:
    include:
        - &STANDARD_TEST_JOB
            stage: Fast Test
            php: 7.0
            install:
                # Composer: enforce given Symfony components version
                - if [ "$SYMFONY_VERSION" != "" ]; then composer global show symfony/flex -q || travis_retry composer global require $DEFAULT_COMPOSER_FLAGS symfony/flex; fi
                - if [ "$SYMFONY_VERSION" != "" ]; then composer config extra.symfony.require $SYMFONY_VERSION || true; fi

                - travis_retry composer update $DEFAULT_COMPOSER_FLAGS $COMPOSER_FLAGS
                - composer info -D | sort
            script:
                - vendor/bin/phpunit || travis_terminate 1
                - PHP_CS_FIXER_FUTURE_MODE=1 php php-cs-fixer --diff --dry-run -v fix

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 5.6
            env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 7.1
            name: 7.1 | Symfony ~4.1.0
            env: SYMFONY_DEPRECATIONS_HELPER=disabled PHP_CS_FIXER_TEST_USE_LEGACY_TOKENIZER=1 SYMFONY_VERSION="~4.1.0"

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 7.2
            name: 7.2 | Symfony ^5.0
            env: SYMFONY_DEPRECATIONS_HELPER=disabled PHP_CS_FIXER_TEST_USE_LEGACY_TOKENIZER=1 SYMFONY_VERSION="^5.0"

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 7.3
            name: 7.3 | With migration rules
            before_script:
                - php php-cs-fixer fix --rules @PHP73Migration,@PHP71Migration:risky,blank_line_after_opening_tag -q || travis_terminate 1

        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: 7.4
            name: 7.4 | Collect coverage
            before_install:
                # for building a tag release we don't need to collect code coverage
                - if [ $TRAVIS_TAG ]; then travis_terminate 0; fi

                ## regular `before_install`
                # turn off XDebug
                - phpenv config-rm xdebug.ini || return 0

                # Require PHPUnit 8
                - composer require --dev --no-update phpunit/phpunit:^8

                # Install PCOV
                - pecl install pcov
            before_script:
                # Make code compatible with PHPUnit 8
                - PHP_CS_FIXER_FUTURE_MODE=1 php php-cs-fixer fix --rules=void_return -q tests || return 0
            script:
                - vendor/bin/phpunit --testsuite coverage --exclude-group covers-nothing --coverage-clover build/logs/clover.xml || travis_terminate 1
                - php vendor/bin/php-coveralls -v

        -
            stage: Deployment
            php: 7.4
            install: ./dev-tools/build.sh
            script:
                - PHP_CS_FIXER_TEST_ALLOW_SKIPPING_SMOKE_TESTS=0 vendor/bin/phpunit tests/Smoke/

            before_deploy:
                # ensure that deployment is happening only if tag matches version of PHP CS Fixer
                - test $(php dev-tools/info-extractor.php | jq .version.vnumber) == "\"$TRAVIS_TAG\""
            deploy:
                provider: releases
                token:
                    secure: K9NKi7X1OPz898fxtVc1RfWrSI+4hTFFYOik932wTz1jC4dQJ64Khh1LV9frA1+JiDS3+R6TvmQtpzbkX3y4L75UrSnP1ADH5wfMYIVmydG3ZjTMo8SWQWHmRMh3ORAKTMMpjl4Q7EkRkLp6RncKe+FAFPP5mgv55mtIMaE4qUk=
                file: php-cs-fixer.phar
                skip_cleanup: true
                on:
                    repo: FriendsOfPHP/PHP-CS-Fixer
                    tags: true
            after_deploy:
                - ./dev-tools/trigger-website.sh ${TRAVIS_TOKEN} ${TRAVIS_TAG}

    allow_failures:
        - php: nightly
